{% set name = "sdsl-lite" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xxsds/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz 
  sha256: 85196ff4e621dbb2cddd80a2a47c6a65854557b27e375999615ae899b233e70b

build:
  number: 0
  script: "$SRC_DIR/install.sh $PREFIX"  # [unix]
  # TODO: fix Windows build/testing
  skip: true  # [win]
  #script: "del %SRC_DIR%\\build\\CMakeCache.txt && %SRC_DIR%\\install.bat %PREFIX%"  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  run:
    - {{ compiler('cxx') }}

test:
  source_files:
    - Make.helper
    - examples
  commands:
    - cd examples && make fm-index.x intersect.x LIB_DIR=$PREFIX/lib INC_DIR=$PREFIX/include

about:
  home: https://github.com/simongog/sdsl-lite
  license: GPL-3
  license_family: GPL
  summary: 'The Succinct Data Structure Library (SDSL)'
  description: |
    The Succinct Data Structure Library (SDSL) is a powerful and flexible C++11
    library implementing succinct data structures. In total, the library contains
    the highlights of 40 research publications. Succinct data structures can
    represent an object (such as a bitvector or a tree) in space close to the
    information-theoretic lower bound of the object while supporting operations of
    the original object efficiently. The theoretical time complexity of an
    operation performed on the classical data structure and the equivalent
    succinct data structure are (most of the time) identical.
  dev_url: https://github.com/simongog/sdsl-lite
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

extra:
  recipe-maintainers:
    - jvolkening
    - johnlees
