{% set name = "sdsl-lite" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xxsds/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7b3281139f7a6c38049e967dcf1ca1d0cc9b65e62153c2ea163d2c8077dd864b

build:
  number: 0
  # TODO: fix Windows build/testing
  skip: true  # [win]
  #script: "del %SRC_DIR%\\build\\CMakeCache.txt && %SRC_DIR%\\install.bat %PREFIX%"  # [win]

test:
  source_files:
    - examples/print_wt.cpp
  requires:
    - {{ compiler('cxx') }}    
  commands:
    - test -d $PREFIX/include/sdsl/sdsl_concepts.hpp
    - $CXX $CPPFLAGS examples/print_wt.cpp

about:
  home: https://github.com/xxsds/sdsl-lite
  license: GPL-3.0-or-later
  license_family: GPL
  summary: 'The Succinct Data Structure Library (SDSL)'
  description: |
    The Succinct Data Structure Library (SDSL) is a powerful and flexible C++11
    library implementing succinct data structures. In total, the library contains
    the highlights of 40 research publications. Succinct data structures can
    represent an object (such as a bitvector or a tree) in space close to the
    information-theoretic lower bound of the object while supporting operations of
    the original object efficiently. The theoretical time complexity of an
    operation performed on the classical data structure and the equivalent
    succinct data structure are (most of the time) identical.
  dev_url: https://github.com/xxsds/sdsl-lite
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

extra:
  recipe-maintainers:
    - jvolkening
    - johnlees
    - yp
    - notestaff
