appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: sdDnmf4QiMWRxiThWDszeFRSHv4j2lulWL6za4qw6Bl51GSyg+DhbRoI3zOlm9HTPa3d2k2SmZTSVzGjNVEZKm6QTpH6htu1Kxfqzxem82MBR7FDm5VUGn4XjCFNVMJScpYNVEQ1NGzvwJUojFEh3bM/S+J8YRkpqy0iHeCLC3b+4MWEM+lrfvfn7HJxPLr8DQMR3XzU//yc2RRA2MbK6YqdUCjz5HpIMHTI7U4RSwM5YkAFiT9icLS9MA3s9U/iw6+3TykhRgxsQX79akYNdxBE5k5jc6qShs955sUWGoAIARLQRhRN9XLBBehQ81G0BDCPG5Sr0dxp3WVmALuUXdEm6dVWxSN9yx3wFCMS1tp8/fngKQ5v0y4mogBaZzSHHytKK9lp2D9wWg7xeY3hOYo26btO49jVLZxXsKeFYRkjKru2E7Xh2utyYB7fhWQ0TFXEQocrx/QEXMXOEPWJOXtNYPfJ6C3/ZgI9ezbEIqN3G1DgYR7hyLNFVqt1fCEJQSBMJT0m5tN47u8uO9jRklkaBxB3mkiCRegFxy8OR83YlAddYAKMo+tHpjFD45tSruG4oXJTR93/h6D7GgHTS19NqvyN/IJI6t/Dk/0dd8BWkBYguEGpJ8A4+wYfvXZCb2sHtpT2p378kBPwe248DuqB28UJbSmmB6XkiQC7lao=}
conda_forge_output_validation: true
